### ISSUE TITLE
不知道为什么hexo s后访问网页就报很多错，是少什么么

### ISSUE THREAD

**Issue by 414871856** [honjun/hexo-theme-sakura#20]

**Comment by Snile826** [comment]
你这样很难让人回复啊，环境摘要么有，错误信息么有。

**Comment by 414871856** [comment]
ERROR Render HTML failed: index.html
TypeError: D:\MyBlog\themes\hexo-theme-sakura-master\layout\layout.ejs:13
    11|     </div>
    12|     <%- partial('_widget/search/insight') %>
 >> 13|     <%- partial('_partial/footer', null, {cache: !config.relative_link}) %>
    14|     <div class="openNav no-select" style="height: 50px;">
    15|       <div class="iconflat no-select" style="width: 50px; height: 50px;">
    16|         <div class="icon"></div>

D:\MyBlog\themes\hexo-theme-sakura-master\layout\_partial\footer.ejs:47
    45| /* <![CDATA[ */
    46| if (/Android|webOS|iPhone|iPod|BlackBerry/i.test(navigator.userAgent)) {
 >> 47|   var Poi = {"pjax":"<%- theme.pjax %>","movies":{"url": "<%- theme.movies.url %>","name":"<%- theme.movies.name%>","live":"close"},"windowheight":"fixed","codelamp":"close","ajaxurl":"","order":"asc","formpostion":"bottom"};
    48| } else {
    49|   var Poi = {"pjax":"<%- theme.pjax %>","movies":{"url": "<%- theme.movies.url %>","name":"<%- theme.movies.name%>","live":"open"},"windowheight":"auto","codelamp":"close","ajaxurl":"","order":"asc","formpostion":"bottom"};
    50| }

Cannot read property 'url' of undefined
    at eval (eval at compile (D:\MyBlog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:30:30)
    at returnedFn (D:\MyBlog\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\MyBlog\node_modules\hexo\lib\theme\view.js:119:22)
    at Theme._View.View.View.renderSync (D:\MyBlog\node_modules\hexo\lib\theme\view.js:48:23)
    at fragment_cache (D:\MyBlog\node_modules\hexo\lib\plugins\helper\partial.js:31:52)
    at Object.fragmentCache (D:\MyBlog\node_modules\hexo\lib\plugins\helper\fragment_cache.js:9:32)
    at Object.partial (D:\MyBlog\node_modules\hexo\lib\plugins\helper\partial.js:31:17)
    at eval (eval at compile (D:\MyBlog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:24:17)
    at returnedFn (D:\MyBlog\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\MyBlog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\MyBlog\node_modules\hexo\lib\theme\view.js:29:15)
    at _compiled.then.result (D:\MyBlog\node_modules\hexo\lib\theme\view.js:40:23)
    at tryCatcher (D:\MyBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\MyBlog\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\MyBlog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\MyBlog\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\MyBlog\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\MyBlog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\MyBlog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\MyBlog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\MyBlog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
Unhandled rejection TypeError: D:\MyBlog\themes\hexo-theme-sakura-master\layout\layout.ejs:13
    11|     </div>
    12|     <%- partial('_widget/search/insight') %>
 >> 13|     <%- partial('_partial/footer', null, {cache: !config.relative_link}) %>
    14|     <div class="openNav no-select" style="height: 50px;">
    15|       <div class="iconflat no-select" style="width: 50px; height: 50px;">
    16|         <div class="icon"></div>

D:\MyBlog\themes\hexo-theme-sakura-master\layout\_partial\footer.ejs:47
    45| /* <![CDATA[ */
    46| if (/Android|webOS|iPhone|iPod|BlackBerry/i.test(navigator.userAgent)) {
 >> 47|   var Poi = {"pjax":"<%- theme.pjax %>","movies":{"url": "<%- theme.movies.url %>","name":"<%- theme.movies.name%>","live":"close"},"windowheight":"fixed","codelamp":"close","ajaxurl":"","order":"asc","formpostion":"bottom"};
    48| } else {
    49|   var Poi = {"pjax":"<%- theme.pjax %>","movies":{"url": "<%- theme.movies.url %>","name":"<%- theme.movies.name%>","live":"open"},"windowheight":"auto","codelamp":"close","ajaxurl":"","order":"asc","formpostion":"bottom"};
    50| }

Cannot read property 'url' of undefined
    at eval (eval at compile (D:\MyBlog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:30:30)
    at returnedFn (D:\MyBlog\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\MyBlog\node_modules\hexo\lib\theme\view.js:119:22)
    at Theme._View.View.View.renderSync (D:\MyBlog\node_modules\hexo\lib\theme\view.js:48:23)
    at fragment_cache (D:\MyBlog\node_modules\hexo\lib\plugins\helper\partial.js:31:52)
    at Object.fragmentCache (D:\MyBlog\node_modules\hexo\lib\plugins\helper\fragment_cache.js:9:32)
    at Object.partial (D:\MyBlog\node_modules\hexo\lib\plugins\helper\partial.js:31:17)
    at eval (eval at compile (D:\MyBlog\node_modules\ejs\lib\ejs.js:633:12), <anonymous>:24:17)
    at returnedFn (D:\MyBlog\node_modules\ejs\lib\ejs.js:668:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\MyBlog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\MyBlog\node_modules\hexo\lib\theme\view.js:29:15)
    at _compiled.then.result (D:\MyBlog\node_modules\hexo\lib\theme\view.js:40:23)
    at tryCatcher (D:\MyBlog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\MyBlog\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (D:\MyBlog\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (D:\MyBlog\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (D:\MyBlog\node_modules\bluebird\js\release\promise.js:699:18)
    at _drainQueueStep (D:\MyBlog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\MyBlog\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\MyBlog\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\MyBlog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)

**Comment by Snile826** [comment]
很明显，是您的配置文件有问题才导致这个Cannot read property 'url' of undefined，我的建议是您先复制一份没问题的配置保证能启动成功，然后再进行修改。在修改的过程中不要随意注释和删除配置项，不需要的可以留个空在那。




------------------ 原始邮件 ------------------
发件人: "谢淮"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 晚上6:06
收件人: "honjun/hexo-theme-sakura"<hexo-theme-sakura@noreply.github.com>;
抄送: "-、Forever in time丶 "<826245622@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [honjun/hexo-theme-sakura] 不知道为什么hexo s后访问网页就报很多错，是少什么么 (#20)




ERROR Render HTML failed: index.html
 TypeError: D:\MyBlog\themes\hexo-theme-sakura-master\layout\layout.ejs:13
 11|     
 12|     <%- partial('_widget/search/insight') %>
   
13|     <%- partial('_partial/footer', null, {cache: !config.relative_link}) %>
 14|     

 15|       
 16|         


 

  
D:\MyBlog\themes\hexo-theme-sakura-master\layout_partial\footer.ejs:47
 45| /* <![CDATA[ */
 46| if (/Android|webOS|iPhone|iPod|BlackBerry/i.test(navigator.userAgent)) {
   
47|   var Poi = {"pjax":"<%- theme.pjax %>","movies":{"url": "<%- theme.movies.url %>","name":"<%- theme.movies.name%>","live":"close"},"windowheight":"fixed","codelamp":"close","ajaxurl":"","order":"asc","formpostion":"bottom"};
 48| } else {
 49|   var Poi = {"pjax":"<%- theme.pjax %>","movies":{"url": "<%- theme.movies.url %>","name":"<%- theme.movies.name%>","live":"open"},"windowheight":"auto","codelamp":"close","ajaxurl":"","order":"asc","formpostion":"bottom"};
 50| }
   
Cannot read property 'url' of undefined
 at eval (eval at compile (D:\MyBlog\node_modules\ejs\lib\ejs.js:633:12), :30:30)
 at returnedFn (D:\MyBlog\node_modules\ejs\lib\ejs.js:668:17)
 at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\MyBlog\node_modules\hexo\lib\theme\view.js:119:22)
 at Theme._View.View.View.renderSync (D:\MyBlog\node_modules\hexo\lib\theme\view.js:48:23)
 at fragment_cache (D:\MyBlog\node_modules\hexo\lib\plugins\helper\partial.js:31:52)
 at Object.fragmentCache (D:\MyBlog\node_modules\hexo\lib\plugins\helper\fragment_cache.js:9:32)
 at Object.partial (D:\MyBlog\node_modules\hexo\lib\plugins\helper\partial.js:31:17)
 at eval (eval at compile (D:\MyBlog\node_modules\ejs\lib\ejs.js:633:12), :24:17)
 at returnedFn (D:\MyBlog\node_modules\ejs\lib\ejs.js:668:17)
 at Theme._View.View._compiled.locals [as _compiled] (D:\MyBlog\node_modules\hexo\lib\theme\view.js:123:48)
 at Theme._View.View.View.render (D:\MyBlog\node_modules\hexo\lib\theme\view.js:29:15)
 at _compiled.then.result (D:\MyBlog\node_modules\hexo\lib\theme\view.js:40:23)
 at tryCatcher (D:\MyBlog\node_modules\bluebird\js\release\util.js:16:23)
 at Promise._settlePromiseFromHandler (D:\MyBlog\node_modules\bluebird\js\release\promise.js:517:31)
 at Promise._settlePromise (D:\MyBlog\node_modules\bluebird\js\release\promise.js:574:18)
 at Promise._settlePromise0 (D:\MyBlog\node_modules\bluebird\js\release\promise.js:619:10)
 at Promise._settlePromises (D:\MyBlog\node_modules\bluebird\js\release\promise.js:699:18)
 at _drainQueueStep (D:\MyBlog\node_modules\bluebird\js\release\async.js:138:12)
 at _drainQueue (D:\MyBlog\node_modules\bluebird\js\release\async.js:131:9)
 at Async._drainQueues (D:\MyBlog\node_modules\bluebird\js\release\async.js:147:5)
 at Immediate.Async.drainQueues [as _onImmediate] (D:\MyBlog\node_modules\bluebird\js\release\async.js:17:14)
 at runCallback (timers.js:705:18)
 Unhandled rejection TypeError: D:\MyBlog\themes\hexo-theme-sakura-master\layout\layout.ejs:13
 11|     
 12|     <%- partial('_widget/search/insight') %>
   
13|     <%- partial('_partial/footer', null, {cache: !config.relative_link}) %>
 14|     

 15|       
 16|         


 

  
D:\MyBlog\themes\hexo-theme-sakura-master\layout_partial\footer.ejs:47
 45| /* <![CDATA[ */
 46| if (/Android|webOS|iPhone|iPod|BlackBerry/i.test(navigator.userAgent)) {
   
47|   var Poi = {"pjax":"<%- theme.pjax %>","movies":{"url": "<%- theme.movies.url %>","name":"<%- theme.movies.name%>","live":"close"},"windowheight":"fixed","codelamp":"close","ajaxurl":"","order":"asc","formpostion":"bottom"};
 48| } else {
 49|   var Poi = {"pjax":"<%- theme.pjax %>","movies":{"url": "<%- theme.movies.url %>","name":"<%- theme.movies.name%>","live":"open"},"windowheight":"auto","codelamp":"close","ajaxurl":"","order":"asc","formpostion":"bottom"};
 50| }
   
Cannot read property 'url' of undefined
 at eval (eval at compile (D:\MyBlog\node_modules\ejs\lib\ejs.js:633:12), :30:30)
 at returnedFn (D:\MyBlog\node_modules\ejs\lib\ejs.js:668:17)
 at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\MyBlog\node_modules\hexo\lib\theme\view.js:119:22)
 at Theme._View.View.View.renderSync (D:\MyBlog\node_modules\hexo\lib\theme\view.js:48:23)
 at fragment_cache (D:\MyBlog\node_modules\hexo\lib\plugins\helper\partial.js:31:52)
 at Object.fragmentCache (D:\MyBlog\node_modules\hexo\lib\plugins\helper\fragment_cache.js:9:32)
 at Object.partial (D:\MyBlog\node_modules\hexo\lib\plugins\helper\partial.js:31:17)
 at eval (eval at compile (D:\MyBlog\node_modules\ejs\lib\ejs.js:633:12), :24:17)
 at returnedFn (D:\MyBlog\node_modules\ejs\lib\ejs.js:668:17)
 at Theme._View.View._compiled.locals [as _compiled] (D:\MyBlog\node_modules\hexo\lib\theme\view.js:123:48)
 at Theme._View.View.View.render (D:\MyBlog\node_modules\hexo\lib\theme\view.js:29:15)
 at _compiled.then.result (D:\MyBlog\node_modules\hexo\lib\theme\view.js:40:23)
 at tryCatcher (D:\MyBlog\node_modules\bluebird\js\release\util.js:16:23)
 at Promise._settlePromiseFromHandler (D:\MyBlog\node_modules\bluebird\js\release\promise.js:517:31)
 at Promise._settlePromise (D:\MyBlog\node_modules\bluebird\js\release\promise.js:574:18)
 at Promise._settlePromise0 (D:\MyBlog\node_modules\bluebird\js\release\promise.js:619:10)
 at Promise._settlePromises (D:\MyBlog\node_modules\bluebird\js\release\promise.js:699:18)
 at _drainQueueStep (D:\MyBlog\node_modules\bluebird\js\release\async.js:138:12)
 at _drainQueue (D:\MyBlog\node_modules\bluebird\js\release\async.js:131:9)
 at Async._drainQueues (D:\MyBlog\node_modules\bluebird\js\release\async.js:147:5)
 at Immediate.Async.drainQueues [as _onImmediate] (D:\MyBlog\node_modules\bluebird\js\release\async.js:17:14)
 at runCallback (timers.js:705:18)

**Comment by 414871856** [comment]
这样啊，我是直接下载zip的，我哪里都没改过就先启动看看就这样了

**Comment by Snile826** [comment]
我也是最近才使用这套主题的，你的错误我也遇到过，不过那是因为我删了一些配置。 之后我直接clone仓库代码稍微改改不删不注释就能直接启动了，zip我没下过，建议试一试最新的仓库代码。------------------ 原始邮件 ------------------
发件人: "谢淮"<notifications@github.com>
发送时间: 2019年6月25日(星期二) 晚上7:05
收件人: "honjun/hexo-theme-sakura"<hexo-theme-sakura@noreply.github.com>;
抄送: "Snile"<826245622@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [honjun/hexo-theme-sakura] 不知道为什么hexo s后访问网页就报很多错，是少什么么 (#20)



这样啊，我是直接下载zip的，我哪里都没改过就先启动看看就这样了
 
&mdash;

**Comment by yinghualuowu** [comment]
我也是刚刚使用，但看demo，每个文章下面都有一个奇怪的错误代码，不知道是啥
