### ISSUE TITLE
渲染博客时报错

### ISSUE THREAD

**Issue by lanjiachen** [honjun/hexo-theme-sakura#64]
`TypeError: Invalid config detected: "url" should be a valid URL!
    at module.exports (C:\Users\Administrator\blog\node_modules\hexo\lib\hexo\validate_config.js:16:11)
    at module.exports (C:\Users\Administrator\blog\node_modules\hexo\lib\hexo\load_config.js:37:3)`

**Comment by lanjiachen** [comment]
`hexo clean`也无法执行

**Comment by liugd2018** [comment]
解决了，我也有这个问题

**Comment by liugd2018** [comment]
解决了吗？我也有这个问题
